### PR TITLE
Add release CI/CD workflow

### PR DESCRIPTION
**Pull request by olisovyi-everstake**
image

### CODE REVIEW

**Review by mksh — APPROVED** [review]
LGTM. Thank you for the contribution!

**Review by jenpaff — APPROVED** [review]

**Comment by mksh** [comment]
Hi @olisovyi-everstake!  Thank you one more time for adding the release job, we would be happy to make use of it going forward.

Can you please pull latest main branch changes into your fork, so CI triggers can run and we can merge your contribution.

Sorry, we originally set CI to only work on branch pushes, but now made it to run on pull requests, so to merge your PR need to update it with the changes to satisfy our required checks.

**Comment by olisovyi-everstake** [comment]
@mksh please check

**Comment by jenpaff** [comment]
it's now failing at cargo-deny vulnerability check- i can provide a PR to fix

**Comment by olisovyi-everstake** [comment]
@jenpaff failing at cargo-deny - I had it initially

**Comment by jenpaff** [comment]
> @jenpaff failing at cargo-deny - I had it initially

I just fixed it on a separate PR, should be able to rebase.

**Comment by jenpaff** [comment]
we made it :) thanks @olisovyi-everstake for your contribution

**Comment by olisovyi-everstake** [comment]
@jenpaff Always happy to contribute)

**Pull request merged**
